MAKEFLAGS += --no-print-directory
#Variables for method of compilation and compilation flags
CC = @gcc
CFLAGS = -Wall -Werror -g

# Linking flags - LDFLAGS
LDFLAGS=
.PHONY: clean rebuild all test 

OBJS = MainGrepText.o ParseFuncArguments.o ParsePhraseToGrep.o
OBJS_TEST1 = ParseFuncArguments.o ParsePhraseToGrep.o ParseFuncArguments_test.o

.c.o:
	$(CC) -c $(CFLAGS) -o $@ $<

TARGET = my_grep

# Receipies:
#all:
all : $(OBJS)
	@$(CC) $(OBJS) -o $(TARGET)
	
clean:
		@rm -f *$(OBJS)
		@rm -f $(TARGET)
		
run: $(TARGET)
	./$(TARGET)

test:
	./run_all.sh

ParseFuncArguments_test: $(OBJS_TEST1)
	@$(CC) $(OBJS_TEST1) -o ParseFuncArguments_test
	
# .o files dependencies
MainGrepText.o: ParseFuncArguments.h
ParseFuncArguments.o: ParseFuncArguments.h ParsePhraseToGrep.h
ParsePhraseToGrep.o: ParsePhraseToGrep.h
